# Generated by Django 3.2.6 on 2022-07-05 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chambre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
                ('prix', models.IntegerField()),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='media/pics')),
            ],
        ),
    ]
