# Generated by Django 3.2.14 on 2022-07-05 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('info', models.TextField()),
                ('address', models.CharField(max_length=300)),
                ('score', models.IntegerField()),
                ('stars', models.IntegerField()),
                ('is_suspend', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=100)),
                ('photo', models.FileField(default='pics/room3.jpg', upload_to='pics/')),
                ('discription', models.TextField()),
                ('cost', models.IntegerField()),
                ('capacity', models.IntegerField()),
                ('is_empty', models.BooleanField(default=True)),
            ],
        ),
    ]
