# Generated by Django 3.2.14 on 2022-07-06 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='photo',
        ),
        migrations.AddField(
            model_name='hotel',
            name='photo',
            field=models.FileField(default='pics/room3.jpg', upload_to='pics/'),
        ),
        migrations.CreateModel(
            name='gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(default='pics/room3.jpg', upload_to='pics/')),
                ('note', models.TextField()),
                ('hotel', models.ForeignKey(on_delete=models.Model, to='hotels.hotel')),
            ],
        ),
    ]
