# Generated by Django 3.2.14 on 2022-07-06 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_contactus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='account',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='account',
            field=models.CharField(max_length=200),
        ),
    ]
