# Generated by Django 3.2.14 on 2022-07-06 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_auto_20220706_0706'),
        ('home', '0003_auto_20220706_0708'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='hotel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hotels.hotel'),
            preserve_default=False,
        ),
    ]
